- name: Instalacja Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Dodanie repozytoriów Helm
  shell: |
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo add jetstack https://charts.jetstack.io
    helm repo update

- name: Instalacja ingress-nginx
  shell: |
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
      --namespace ingress-nginx --create-namespace \
      --set controller.hostNetwork=true \
      --set controller.kind=DaemonSet \
      --set controller.service.type=ClusterIP
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Czekaj aż ingress-nginx-controller będzie gotowy
  shell: |
    kubectl wait --namespace ingress-nginx \
      --for=condition=ready pod \
      --selector=app.kubernetes.io/component=controller \
      --timeout=120s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Instalacja cert-manager
  shell: |
    helm upgrade --install cert-manager jetstack/cert-manager \
      --namespace cert-manager --create-namespace \
      --set crds.enabled=true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Czekaj aż cert-manager będzie gotowy
  shell: |
    kubectl wait --namespace cert-manager \
      --for=condition=ready pod \
      --selector=app.kubernetes.io/instance=cert-manager \
      --timeout=120s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml