namespace: "{{ vault_namespace }}"
domain: "{{ vault_domain }}"
email: "{{ vault_email }}"

mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_user_password: "{{ vault_mysql_user_password }}"
mysql_user_name: "{{ vault_mysql_user_name }}"
mysql_database: "{{ vault_mysql_database }}"