---
- hosts: k8s
  become: true

  vars:
    swapfile_path: /swapfile
    swapfile_size: "{{ (ansible_memtotal_mb <= 4096) | ternary(ansible_memtotal_mb, (ansible_memtotal_mb / 2) | int) }}"

  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

  roles:
    - swap
    - k3s
    - helm
    - k8s
    - mysql