server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/javascript image/svg+xml;
    gzip_min_length 1024;

    # Static assets cache
    location ~* \.(css|js|png|gif|ico|jpg|jpeg|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # Files 
    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    # PHP connection
    location ~ \.php$ {
        fastcgi_pass php-svc:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        # Path to php files in php contener
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;

        #  User IP for php sctipt
        fastcgi_param HTTP_X_REAL_IP  $http_x_real_ip;

        # Timeouts
        fastcgi_connect_timeout 5s;
        fastcgi_read_timeout    10s;
    }

    # Deny acces to other files
    location ~ /\. {
        deny all;
    }
}

# Secound server for redirect github.*
server {
    listen 80;
    server_name github.*;

    location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location / {
        add_header X-Robots-Tag "noindex, nofollow" always;
        
        fastcgi_pass      php-svc:9000;
        include           fastcgi_params;
        fastcgi_param     SCRIPT_FILENAME /var/www/html/api/redirect.php;
        fastcgi_param     REQUEST_URI     $request_uri;
        fastcgi_param     HTTP_X_REAL_IP  $http_x_real_ip;
    }
}