- name: Tworzenie katalogu na manifesty
  file:
    path: /home/ubuntu/manifests
    state: directory
    owner: ubuntu

- name: Renderowanie szablonów Jinja2
  template:
    src: "{{ item }}"
    dest: "/home/ubuntu/manifests/{{ item | basename | replace('.j2', '') }}"
  with_fileglob:
    - "../../../../k8s/manifests/*.yml.j2"

- name: Aplikowanie Namespace
  shell: kubectl apply -f /home/ubuntu/manifests/namespace.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie ClusterIssuer
  shell: kubectl apply -f /home/ubuntu/manifests/clusterissuer.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Tworzenie Secret dla MySQL
  shell: |
    kubectl create secret generic mysql-credentials \
      --from-literal=MYSQL_HOST="mysql-svc" \
      --from-literal=MYSQL_DATABASE="{{ mysql_database }}" \
      --from-literal=MYSQL_USER="{{ mysql_user_name }}" \
      --from-literal=MYSQL_PASSWORD="{{ mysql_user_password }}" \
      --from-literal=DB_PORT="3306" \
      --namespace="{{ namespace }}" \
      --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  no_log: true

- name: Aplikowanie Service MySQL
  shell: kubectl apply -f /home/ubuntu/manifests/service-mysql.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Deployment Nginx
  shell: kubectl apply -f /home/ubuntu/manifests/deployment-nginx.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Deployment PHP
  shell: kubectl apply -f /home/ubuntu/manifests/deployment-php.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Service Nginx
  shell: kubectl apply -f /home/ubuntu/manifests/service-nginx.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Service PHP
  shell: kubectl apply -f /home/ubuntu/manifests/service-php.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Ingress
  shell: kubectl apply -f /home/ubuntu/manifests/ingress.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config