- name: Tworzenie katalogu na manifesty
  file:
    path: /home/ubuntu/manifests
    state: directory
    owner: ubuntu

- name: Renderowanie szablonów Jinja2
  template:
    src: "{{ item }}"
    dest: "/home/ubuntu/manifests/{{ item | basename | replace('.j2', '') }}"
  with_fileglob:
    - "../../../../k8s/manifests/*.yml.j2"

- name: Aplikowanie Namespace
  shell: kubectl apply -f /home/ubuntu/manifests/namespace.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie ClusterIssuer
  shell: kubectl apply -f /home/ubuntu/manifests/clusterissuer.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Secret - MySQL Credentials
  shell: kubectl apply -f /home/ubuntu/manifests/secret-mysql.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Deployment Nginx
  shell: kubectl apply -f /home/ubuntu/manifests/deployment-nginx.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Deployment PHP
  shell: kubectl apply -f /home/ubuntu/manifests/deployment-php.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Service Nginx
  shell: kubectl apply -f /home/ubuntu/manifests/service-nginx.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Service PHP
  shell: kubectl apply -f /home/ubuntu/manifests/service-php.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Aplikowanie Ingress
  shell: kubectl apply -f /home/ubuntu/manifests/ingress.yml
  become_user: ubuntu
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config